
-- 조건에 부합하는 중고거래 상태 조회하기

SELECT BOARD_ID, WRITER_ID, TITLE, PRICE
        ,CASE WHEN STATUS = 'RESERVED' THEN '예약중'
              WHEN STATUS = 'SALE' THEN '판매중'
              WHEN STATUS = 'DONE' THEN '거래완료' END AS STATUS
  FROM USED_GOODS_BOARD
 WHERE CREATED_DATE = '2022-10-05'
 ORDER BY 1 DESC

 -- 오랜 기간 보호한 동물(2)

 SELECT ANIMAL_ID, NAME
  FROM
    (
    SELECT A.ANIMAL_ID, A.NAME
            , DENSE_RANK() OVER(ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC) AS RNK
      FROM ANIMAL_INS A
      LEFT JOIN ANIMAL_OUTS B
        ON A.ANIMAL_ID = B.ANIMAL_ID
    ) TB
 WHERE RNK <= 2

 -- 카테고리 별 상품 개수 구하기

 SELECT LEFT(PRODUCT_CODE,2) AS CATEGORY, COUNT(DISTINCT PRODUCT_CODE)
  FROM PRODUCT
 GROUP BY LEFT(PRODUCT_CODE,2)
 ORDER BY 1